"""Add date_registered to User

Revision ID: 4af5532396a2
Revises: df84e64ea8e1
Create Date: 2024-10-06 01:29:23.444502

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func


# revision identifiers, used by Alembic.
revision = '4af5532396a2'
down_revision = 'df84e64ea8e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Add date_registered column with default value for existing rows
        batch_op.add_column(sa.Column('date_registered', sa.DateTime(), nullable=False, server_default=sa.func.now()))

    # ### end Alembic commands ###

    # Optional: Remove the server default afterward if not needed
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('date_registered', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('date_registered')

    # ### end Alembic commands ###

